# Generated by Django 3.2.8 on 2021-11-30 22:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mail', models.CharField(max_length=48)),
            ],
        ),
        migrations.CreateModel(
            name='ForestryMap',
            fields=[
                ('forestry', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='forestry_map', serialize=False, to='main.forestry', verbose_name='Forestry')),
                ('map_geojson', models.JSONField(verbose_name='Map_geojson')),
            ],
        ),
        migrations.CreateModel(
            name='NotificationType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msg', models.CharField(max_length=48)),
            ],
        ),
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=48)),
                ('x', models.CharField(max_length=24)),
                ('y', models.CharField(max_length=24)),
                ('z', models.CharField(max_length=24)),
                ('forestry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.forestry')),
            ],
        ),
        migrations.CreateModel(
            name='SensorType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=48)),
                ('unit', models.CharField(max_length=12)),
                ('max_std_value', models.CharField(max_length=48)),
                ('min_std_value', models.CharField(max_length=48)),
            ],
        ),
        migrations.CreateModel(
            name='SensorData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('value', models.CharField(max_length=48)),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.sensor')),
            ],
        ),
        migrations.AddField(
            model_name='sensor',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.sensortype'),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sensor_data_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.sensordata')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.notificationtype')),
            ],
        ),
    ]
