# Generated by Django 3.2.8 on 2021-11-30 23:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_sensors_notifications_maps'),
    ]

    operations = [
        migrations.CreateModel(
            name='ForestryResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.SmallIntegerField(choices=[(1, 'Standard_resource'), (2, 'Animal')], default=1, verbose_name='Resource_type')),
                ('name', models.CharField(max_length=128, verbose_name='Resource_name')),
                ('quantity', models.FloatField(verbose_name='Resource_quantity')),
                ('quantity_unit', models.CharField(blank=True, default=None, max_length=32, null=True, verbose_name='Resource_quantity_unit')),
                ('forestry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forestry_resources', to='main.forestry', verbose_name='Forestry')),
            ],
        ),
    ]
