# Generated by Django 3.2.8 on 2021-12-16 20:06

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


def forward_create_default_data(apps, schema_editor):
    PlantType = apps.get_model("main", "PlantType")
    ActionType = apps.get_model("main", "ActionType")

    db_alias = schema_editor.connection.alias

    plant_types = (
        PlantType(id=1, name="Sosna"),
        PlantType(id=2, name="Świerk"),
        PlantType(id=3, name="Jodła"),
        PlantType(id=4, name="Klon"),
        PlantType(id=5, name="Brzoza"),
        PlantType(id=6, name="Dąb")
    )
    action_types = (
        ActionType(id=1, name="Forestation"),
        ActionType(id=2, name="Deforestation")
    )

    PlantType.objects.using(db_alias).bulk_create(plant_types)
    ActionType.objects.using(db_alias).bulk_create(action_types)


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_forestryresource'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=48, unique=True, verbose_name='Action_type')),
            ],
        ),
        migrations.CreateModel(
            name='ForestryAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(blank=True, default=None, null=True, verbose_name='Start_date')),
                ('end_date', models.DateTimeField(blank=True, default=None, null=True, verbose_name='End_date')),
                ('region', models.JSONField(blank=True, default=None, null=True, verbose_name='Region')),
                ('number_of_trees', models.IntegerField(blank=True, default=None, null=True, verbose_name='Number_of_trees')),
                ('action_type', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='forestry_actions', to='main.actiontype', verbose_name='Action_type')),
            ],
        ),
        migrations.CreateModel(
            name='NotificationData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='PlantType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=48, unique=True, verbose_name='Plant_type')),
            ],
        ),
        migrations.RemoveField(
            model_name='notification',
            name='sensor_data_id',
        ),
        migrations.AddField(
            model_name='notification',
            name='additional_data',
            field=models.JSONField(blank=True, default=None, null=True, verbose_name='Additional_data'),
        ),
        migrations.AddField(
            model_name='notification',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notification',
            name='for_sensor',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='sensor_notifications', to='main.sensor', verbose_name='For_sensor'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notification',
            name='message',
            field=models.CharField(blank=True, default=None, max_length=1024, null=True, verbose_name='Message'),
        ),
        migrations.AlterField(
            model_name='email',
            name='mail',
            field=models.EmailField(max_length=256),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.SmallIntegerField(choices=[(0, 'Dev'), (1, 'Information'), (2, 'Warning'), (3, 'Critical')], default=1, verbose_name='Notification_type'),
        ),
        migrations.AlterField(
            model_name='sensordata',
            name='sensor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sensor_measurements', to='main.sensor'),
        ),
        migrations.DeleteModel(
            name='NotificationType',
        ),
        migrations.AddField(
            model_name='notificationdata',
            name='notification_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.notification'),
        ),
        migrations.AddField(
            model_name='notificationdata',
            name='sensor_data_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.sensordata'),
        ),
        migrations.AddField(
            model_name='forestryaction',
            name='plant_type',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='forestry_actions', to='main.planttype', verbose_name='Plant_type'),
        ),
        migrations.RunPython(forward_create_default_data, reverse_code=migrations.RunPython.noop)
    ]
